name: lochness
version: 0.0.1
description: A sample command-line application.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  fuzzylogic:
    path: ../fuzzylogic
  quiver: any
  logging: any
  egamebook:
    path: ../egamebook/dart

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
