name: lochness
version: 1.0.0
description: An egamebook that was originally created for a Ludum Dare.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: http://www.egamebook.com/lochness

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  egamebook:
    path: ../egamebook
  fuzzylogic: any
  quiver: any
